# Generated by Django 4.2.2 on 2023-07-07 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='follow',
            field=models.ManyToManyField(related_name='follow_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
